# Site settings
title: namtzigla
email: florin.stan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  random stuff that I've stuble upon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://namtzigla.github.io" # the base hostname & protocol for your site
twitter_username: namtzigla
github_username:  namtzigla

# Build settings
markdown: kramdown
